name: DelicateX
version: '${project.version}'
main: com.thesilentnights.delicatex.DelicateX
api-version: '1.19'

commands:
  privateMsg:
    permission: player
    description: none
    usage: none
  distance:
    permission: op
    description: none
    usage: none
  entityCounter:
    permission: op
    description: none
    usage: none
  scheduledReboot:
    permission: op
    description: create a task that will shutdown the server in the future
    usage: /scheduledreboot [time(seconds)] [if-broadcast]
  entityClear:
    permission: op
    description: none
    usage: none
  ipLocation:
    permission: op
    description: none
    usage: executing...
  broadcast:
    permission: op
    description: none
    usage: none
default-permission:
  op