name: DelicateX
version: '${project.version}'
main: com.thesilentnights.delicatex.DelicateX
api-version: '1.19'

commands:
  privateMsg:
    permission: player
    aliases: [ pMsg ]
    description: none
    usage: /privateMsg
  distance:
    description: none
    usage: none
  entityCounter:
    description: none
    usage: none
  scheduledReboot:
    description: create a task that will shutdown the server in the future
    usage: /scheduledreboot [time(seconds)] [if-broadcast]
  entityClear:
    description: none
    usage: none
  ipLocation:
    description: none
    usage: executing...
  broadcast:
    description: none
    aliases: [ shout ]
    usage: none
  enchant:
    description: none
    usage: none
  inventoryViewer:
    description: none
    usage: none
    aliases: [ open ]
  cdk:
    description: none
    usage: none
default-permission:
  op