name: AdminToolsPack
version: '${project.version}'
main: com.thesilentnights.admintoolspack.AdminToolsPack
api-version: '1.19'

commands:
  distance:
    permission: op
    description: none
    usage: none
  entityCounter:
    permission: op
    description: none
    usage: none
  scheduledReboot:
    permission: op
    description: create a task that will shutdown the server in the future
    usage: /scheduledreboot [time(seconds)] [if-broadcast]
  entityClear:
    permission: op
    description: none
    usage: none
default-permission:
  op