name: AdminToolsPack
version: '${project.version}'
main: com.thesilentnights.admintoolspack.AdminToolsPack
api-version: '1.19'
commands:
  distance:
    usage: 请于第二目标点再次输入/distance以计算 (以当前玩家脚部方块的坐标为准)
    description: none
